-- Master Schema for Cristian Quiroz and Content Manager Dashboards

---------------------------------------------------------
-- 1. Dashboard Cristian Quiroz (Perfil y Apariciones)
---------------------------------------------------------

CREATE TABLE IF NOT EXISTS content_manager_quiroz_profile (
    id TEXT PRIMARY KEY, -- 'main'
    nombre TEXT DEFAULT 'Cristian Quiroz',
    cargo TEXT DEFAULT 'Registrador Nacional del Estado Civil',
    desde TEXT DEFAULT 'Diciembre 2023',
    partido TEXT DEFAULT 'Independiente',
    declaraciones INTEGER DEFAULT 0,
    apariciones INTEGER DEFAULT 0,
    cuentas_verificadas INTEGER DEFAULT 0,
    entrevistas_tv INTEGER DEFAULT 0,
    menciones_totales INTEGER DEFAULT 0,
    sentimiento_positivo INTEGER DEFAULT 0,
    sentimiento_neutral INTEGER DEFAULT 0,
    sentimiento_negativo INTEGER DEFAULT 0,
    semanal_menciones JSONB DEFAULT '[]'
);

CREATE TABLE IF NOT EXISTS content_manager_quiroz_apariciones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medio TEXT NOT NULL,
    fecha TEXT NOT NULL,
    tema TEXT NOT NULL,
    sentimiento TEXT DEFAULT 'neutral'
);

CREATE TABLE IF NOT EXISTS content_manager_quiroz_strategy (
    id TEXT PRIMARY KEY, -- 'main'
    narrativa JSONB DEFAULT '{}',
    pilares JSONB DEFAULT '[]',
    noticias JSONB DEFAULT '[]',
    contenido JSONB DEFAULT '{}',
    conversacion JSONB DEFAULT '{}',
    pauta JSONB DEFAULT '[]'
);

---------------------------------------------------------
-- 2. Conversación en Redes Sociales
---------------------------------------------------------

CREATE TABLE IF NOT EXISTS content_manager_social_profiles (
    id TEXT PRIMARY KEY, -- 'instagram', 'facebook', 'x', 'tiktok'
    seguidores TEXT DEFAULT '0',
    interacciones INTEGER DEFAULT 0,
    alcance TEXT DEFAULT '0',
    posts INTEGER DEFAULT 0,
    sentimiento INTEGER DEFAULT 0,
    tendencia JSONB DEFAULT '[]',
    top_posts JSONB DEFAULT '[]'
);

CREATE TABLE IF NOT EXISTS content_manager_social_feed (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    red TEXT NOT NULL,
    usuario TEXT NOT NULL,
    tiempo TEXT NOT NULL,
    texto TEXT NOT NULL,
    tipo TEXT DEFAULT 'neutral'
);

---------------------------------------------------------
-- 3. Conversación en Medios
---------------------------------------------------------

CREATE TABLE IF NOT EXISTS content_manager_medios_profiles (
    id TEXT PRIMARY KEY, -- 'kpi_impacto', 'kpi_notas', etc.
    label TEXT NOT NULL,
    value TEXT DEFAULT '0',
    delta TEXT DEFAULT '0%',
    sentimiento INTEGER DEFAULT 0,
    notas INTEGER DEFAULT 0,
    tendencia_semanal JSONB DEFAULT '[]'
);

CREATE TABLE IF NOT EXISTS content_manager_medios_feed (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medio TEXT NOT NULL,
    tiempo TEXT NOT NULL,
    texto TEXT NOT NULL,
    tipo TEXT DEFAULT 'neutral'
);

---------------------------------------------------------
-- Datos Iniciales (Opcional)
---------------------------------------------------------

-- Perfil Quiroz
INSERT INTO content_manager_quiroz_profile (id, nombre, cargo, desde, partido, declaraciones, apariciones, cuentas_verificadas, entrevistas_tv, menciones_totales, sentimiento_positivo, sentimiento_neutral, sentimiento_negativo, semanal_menciones) VALUES
('main', 'Cristian Quiroz', 'Registrador Nacional del Estado Civil', 'Diciembre 2023', 'Independiente', 134, 89, 12, 47, 8421, 52, 31, 17, '[{"dia": "Lun", "n": 450}, {"dia": "Mar", "n": 680}, {"dia": "Mie", "n": 520}, {"dia": "Jue", "n": 890}, {"dia": "Vie", "n": 710}, {"dia": "Sab", "n": 320}, {"dia": "Dom", "n": 240}]')
ON CONFLICT (id) DO NOTHING;

-- Estrategia Quiroz
INSERT INTO content_manager_quiroz_strategy (id, narrativa, pilares, noticias, contenido, pauta) VALUES
('main', 
 '{"gancho": "Cristian Quiroz lidera la transformación digital de la Registraduría con plenas garantías de transparencia.", "tipoConversacion": "Liderazgo + Tecnología + Transparencia", "mensajeClave": "Garantía total para la democracia del 2026.", "arco": [{"fase": "Expectativa", "tipo": "informativo", "mensaje": "Anuncio de las nuevas auditorías internacionales."}, {"fase": "Crecimiento", "tipo": "accion", "mensaje": "Despliegue regional de los kits de biometría."}, {"fase": "Clímax", "tipo": "resultado", "mensaje": "Éxito total en el primer simulacro nacional."}, {"fase": "Consolidación", "tipo": "confianza", "mensaje": "Respaldo unánime de los organismos internacionales."}]}',
 '[{"pilar": "Modernización", "icono": "💻", "color": "#2b82ee", "description": "Uso de IA y biometría para blindar el voto."}, {"pilar": "Transparencia", "icono": "🔍", "color": "#f3b116", "description": "Auditorías abiertas y datos en tiempo real."}, {"pilar": "Cercanía", "icono": "🤝", "color": "#2eb88a", "description": "Diálogo permanente con partidos y ciudadanía."}]',
 '[{"medio": "El Tiempo", "titulo": "Quiroz garantiza que no habrá fallos en el escrutinio", "fecha": "Hace 2h", "categoria": "Electoral", "url": "#"}, {"medio": "Semana", "titulo": "El plan del Registrador para combatir la desinformación", "fecha": "Hace 4h", "categoria": "Seguridad", "url": "#"}]',
 '{"instagram": [{"formato": "Reel", "idea": "Detrás de cámaras: Cómo se protege tu voto", "tipo": "Orgánico"}], "facebook": [{"formato": "Video", "idea": "Tutorial de inscripción de cédulas", "tipo": "Educativo"}], "x": [{"formato": "Hilo", "idea": "10 mitos vs realidades sobre el software", "tipo": "Informativo"}], "tiktok": [{"formato": "Trend", "idea": "Mi día como registrador", "tipo": "Humor/Edu"}]}',
 '[{"formato": "Carousel", "objetivo": "Conversión", "presupuesto": "Alto", "cta": "Inscríbete aquí", "segmento": "Jóvenes 18-25", "plataforma": ["Instagram", "Facebook"]}]'
) ON CONFLICT (id) DO NOTHING;

-- Perfiles Sociales
INSERT INTO content_manager_social_profiles (id, seguidores, sentimiento, interacciones, alcance, posts) VALUES
('instagram', '1.2M', 75, 45000, '2.5M', 124),
('facebook', '2.5M', 62, 32000, '3.8M', 89),
('x', '840K', 48, 120000, '5.2M', 450),
('tiktok', '1.5M', 82, 250000, '12M', 56)
ON CONFLICT (id) DO NOTHING;

-- Perfiles Medios KPIs
INSERT INTO content_manager_medios_profiles (id, label, value, delta, sentimiento, notas, tendencia_semanal) VALUES
('kpi_impacto', 'Impacto Mediático', '8.4M', '+12%', 65, 0, '[]'),
('kpi_notas', 'Notas Publicadas', '342', '+5%', 0, 0, '[{"dia": "Lun", "notas": 45, "positivas": 30, "negativas": 5}, {"dia": "Mar", "notas": 52, "positivas": 35, "negativas": 8}, {"dia": "Mie", "notas": 48, "positivas": 28, "negativas": 10}, {"dia": "Jue", "notas": 65, "positivas": 40, "negativas": 12}, {"dia": "Vie", "notas": 58, "positivas": 38, "negativas": 7}, {"dia": "Sab", "notas": 34, "positivas": 20, "negativas": 4}, {"dia": "Dom", "notas": 40, "positivas": 25, "negativas": 6}]'),
('kpi_voceros', 'Voceros Activos', '12', '+0%', 80, 0, '[]'),
('kpi_alcance', 'Alcance Radial', '4.2M', '+8%', 72, 0, '[]')
ON CONFLICT (id) DO NOTHING;
