-- Tabla para los KPIs de Elecciones
CREATE TABLE IF NOT EXISTS content_manager_elecciones_kpis (
    id TEXT PRIMARY KEY, -- 'potencial', 'mesas', 'candidatos', 'dias'
    label TEXT NOT NULL,
    value TEXT NOT NULL,
    delta TEXT,
    trend TEXT CHECK (trend IN ('up', 'down', 'neutral')),
    progress INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Datos iniciales (migrando los mocks)
INSERT INTO content_manager_elecciones_kpis (id, label, value, delta, trend, progress) VALUES
('potencial', 'Potencial Electoral', '38.8M', '+2.4%', 'up', 70),
('mesas', 'Mesas Habilitadas', '115,432', '+1.1%', 'up', 70),
('candidatos', 'Candidatos Presidenciales', '18', '+3', 'up', 70),
('dias', 'Días para Elección', '247', NULL, 'neutral', 70)
ON CONFLICT (id) DO UPDATE SET
    value = EXCLUDED.value,
    delta = EXCLUDED.delta,
    trend = EXCLUDED.trend,
    progress = EXCLUDED.progress;

-- Tabla para Calendario Electoral
CREATE TABLE IF NOT EXISTS content_manager_calendario_electoral (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha TEXT NOT NULL,
    evento TEXT NOT NULL,
    estado TEXT CHECK (estado IN ('completado', 'activo', 'pendiente', 'en-curso')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Datos iniciales
INSERT INTO content_manager_calendario_electoral (fecha, evento, estado) VALUES
('Ene 2026', 'Cierre inscripción candidatos', 'completado'),
('Feb 2026', 'Inicio campaña electoral', 'completado'),
('Mar 2026', 'Debate presidencial CNE', 'en-curso'),
('Abr 2026', 'Auditorías software votación', 'pendiente'),
('25 May 2026', 'Jornada electoral 1ra vuelta', 'pendiente'),
('Jun 2026', '2da vuelta (si aplica)', 'pendiente');
