-- Tabla para las métricas de Medios (KPIs y Top Medios)
CREATE TABLE IF NOT EXISTS content_manager_medios_profiles (
    id TEXT PRIMARY KEY, -- 'cobertura_total', 'alcance_estimado', 'sentimiento_promedio', 'top_prensa', 'top_radio', etc.
    label TEXT NOT NULL,
    value TEXT DEFAULT '0',
    delta TEXT DEFAULT '0%',
    sentimiento INTEGER DEFAULT 50,
    notas INTEGER DEFAULT 0,
    tendencia_semanal JSONB DEFAULT '[]' -- Datos para el gráfico de barras
);

-- Tabla para el feed de Noticias / Notas de Prensa
CREATE TABLE IF NOT EXISTS content_manager_medios_feed (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medio TEXT NOT NULL,      -- 'El Tiempo', 'Semana', 'RCN', etc.
    usuario TEXT DEFAULT 'Redacción',
    tiempo TIMESTAMPTZ NOT NULL DEFAULT now(),
    texto TEXT NOT NULL,    -- Titular de la noticia
    tipo TEXT DEFAULT 'neutral', -- 'positivo', 'negativo', 'neutral'
    link TEXT DEFAULT '#'
);

-- Datos iniciales para KPIs y perfiles de medios
INSERT INTO content_manager_medios_profiles (id, label, value, delta, sentimiento, notas, tendencia_semanal) VALUES
('kpi_notas', 'Total Notas', '1,284', '+12.5%', 64, 1284, '[{"dia": "Lun", "notas": 150, "positivas": 100, "negativas": 20}, {"dia": "Mar", "notas": 230, "positivas": 140, "negativas": 30}, {"dia": "Mie", "notas": 180, "positivas": 110, "negativas": 15}, {"dia": "Jue", "notas": 290, "positivas": 180, "negativas": 40}, {"dia": "Vie", "notas": 210, "positivas": 130, "negativas": 25}, {"dia": "Sab", "notas": 120, "positivas": 80, "negativas": 10}, {"dia": "Dom", "notas": 90, "positivas": 50, "negativas": 5}]'),
('kpi_alcance', 'Alcance Estimado', '4.2M', '+8.2%', 50, 0, '[]'),
('kpi_sentimiento', 'Sentimiento Gral', '62%', '+5.0%', 62, 0, '[]'),
('kpi_temas', 'Temas Críticos', '18', '-2.0%', 40, 0, '[]'),
('el_tiempo', 'El Tiempo', '245', '78%', 78, 245, '[]'),
('semana', 'Revista Semana', '189', '65%', 65, 189, '[]'),
('rcn', 'RCN Noticias', '156', '72%', 72, 156, '[]'),
('caracol', 'Caracol Radio', '142', '81%', 81, 142, '[]'),
('la_w', 'La W Radio', '128', '69%', 69, 128, '[]')
ON CONFLICT (id) DO NOTHING;

-- Datos iniciales para el feed de noticias (usando timestamps reales)
INSERT INTO content_manager_medios_feed (medio, tiempo, texto, tipo) VALUES
('El Tiempo', now() - interval '5 minutes', 'CNE ratifica plenas garantías para el Software de escrutinio nacional.', 'positivo'),
('Semana', now() - interval '15 minutes', 'Polémica por demora en la entrega de formularios E-14 en zonas rurales.', 'negativo'),
('La W Radio', now() - interval '30 minutes', 'Expertos internacionales avalan el proceso de testigos electorales en Colombia.', 'positivo'),
('Caracol Radio', now() - interval '1 hour', 'Inicia la cuenta regresiva para el gran simulacro de votación del domingo.', 'neutral'),
('La Silla Vacía', now() - interval '2 hours', 'Así se mueve la narrativa de desinformación en medios digitales sobre el CNE.', 'negativo');
