-- Tabla para las métricas de perfiles por red social
CREATE TABLE IF NOT EXISTS content_manager_social_profiles (
    id TEXT PRIMARY KEY, -- 'instagram', 'facebook', 'x', 'tiktok'
    seguidores TEXT DEFAULT '0',
    sentimiento INTEGER DEFAULT 50,
    interacciones INTEGER DEFAULT 0,
    alcance TEXT DEFAULT '0',
    posts INTEGER DEFAULT 0,
    tendencia JSONB DEFAULT '[]', -- Histórico para el mini-gráfico
    top_posts JSONB DEFAULT '[]'   -- Los posts con más impacto de esa red
);

-- Tabla para el feed de mensajes en tiempo real
CREATE TABLE IF NOT EXISTS content_manager_social_feed (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    red TEXT NOT NULL,      -- 'Instagram', 'Facebook', 'X', 'TikTok'
    usuario TEXT NOT NULL,
    tiempo TEXT NOT NULL,   -- 'Hace 2 min', '14:30', etc.
    texto TEXT NOT NULL,
    tipo TEXT DEFAULT 'neutral' -- 'positivo', 'negativo', 'neutral'
);

-- Datos iniciales para perfiles
INSERT INTO content_manager_social_profiles (id, seguidores, sentimiento, interacciones, alcance, posts, tendencia, top_posts) VALUES
('instagram', '1.2M', 64, 45200, '2.5M', 124, '[{"mentions": 10}, {"mentions": 25}, {"mentions": 15}, {"mentions": 30}, {"mentions": 20}]', '[{"texto": "Gran movilización por la transparencia electoral #CNE", "likes": 4200, "comments": 350}]'),
('facebook', '850K', 45, 32100, '1.8M', 89, '[{"mentions": 30}, {"mentions": 10}, {"mentions": 20}, {"mentions": 15}, {"mentions": 25}]', '[{"texto": "Tutorial: ¿Cómo verificar tu puesto de votación?", "likes": 2800, "comments": 120}]'),
('x', '2.4M', 32, 128400, '12M', 452, '[{"mentions": 40}, {"mentions": 60}, {"mentions": 30}, {"mentions": 70}, {"mentions": 50}]', '[{"texto": "ÚLTIMA HORA: CNE anuncia nuevas garantías para testigos", "likes": 15600, "comments": 2400}]'),
('tiktok', '3.1M', 71, 98200, '8.4M', 67, '[{"mentions": 20}, {"mentions": 40}, {"mentions": 60}, {"mentions": 50}, {"mentions": 80}]', '[{"texto": "Mi experiencia como testigo electoral #Elecciones2026", "likes": 125000, "comments": 8200}]')
ON CONFLICT (id) DO NOTHING;

-- Datos iniciales para el feed
INSERT INTO content_manager_social_feed (red, usuario, tiempo, texto, tipo) VALUES
('X', 'PortalEleccion', 'HACE 2 MIN', 'Confirmado el despliegue del 100% de la infraestructura para el preconteo.', 'positivo'),
('Instagram', 'InfoCiudadana', 'HACE 5 MIN', 'La participación juvenil en los simulacros supera las expectativas de 2022.', 'positivo'),
('X', 'CriticaVoto', 'HACE 12 MIN', 'Reportan inconsistencias en el aplicativo de capacitación en algunas zonas.', 'negativo'),
('Facebook', 'CNE_Colombia', 'HACE 20 MIN', 'Inicia la auditoría internacional de software de escrutinio con presencia de partidos.', 'neutral'),
('TikTok', 'VotoJovenCol', 'HACE 45 MIN', 'Todo lo que necesitas saber sobre el carnet de testigo electoral en 60 segundos.', 'positivo');
