-- Tabla para las métricas generales de Cristian Quiroz
CREATE TABLE IF NOT EXISTS content_manager_quiroz_profile (
    id TEXT PRIMARY KEY, -- 'main'
    nombre TEXT DEFAULT 'Cristian Quiroz',
    cargo TEXT DEFAULT 'Registrador Nacional del Estado Civil',
    desde TEXT DEFAULT 'Diciembre 2023',
    partido TEXT DEFAULT 'Independiente',
    declaraciones INTEGER DEFAULT 0,
    apariciones INTEGER DEFAULT 0,
    cuentas_verificadas INTEGER DEFAULT 0,
    entrevistas_tv INTEGER DEFAULT 0,
    menciones_totales INTEGER DEFAULT 0,
    sentimiento_positivo INTEGER DEFAULT 0,
    sentimiento_neutral INTEGER DEFAULT 0,
    sentimiento_negativo INTEGER DEFAULT 0,
    semanal_menciones JSONB DEFAULT '[]' -- Datos para el gráfico de barras
);

-- Tabla para las apariciones en medios de Cristian Quiroz
CREATE TABLE IF NOT EXISTS content_manager_quiroz_apariciones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medio TEXT NOT NULL,
    fecha TEXT NOT NULL,
    tema TEXT NOT NULL,
    sentimiento TEXT DEFAULT 'neutral' -- 'positivo', 'negativo', 'neutral'
);

-- Insertar datos iniciales para Cristian Quiroz
INSERT INTO content_manager_quiroz_profile (id, nombre, cargo, desde, partido, declaraciones, apariciones, cuentas_verificadas, entrevistas_tv, menciones_totales, sentimiento_positivo, sentimiento_neutral, sentimiento_negativo, semanal_menciones) VALUES
('main', 'Cristian Quiroz', 'Registrador Nacional del Estado Civil', 'Diciembre 2023', 'Independiente', 134, 89, 12, 47, 8421, 52, 31, 17, '[{"dia": "Lun", "n": 450}, {"dia": "Mar", "n": 680}, {"dia": "Mie", "n": 520}, {"dia": "Jue", "n": 890}, {"dia": "Vie", "n": 710}, {"dia": "Sab", "n": 320}, {"dia": "Dom", "n": 240}]')
ON CONFLICT (id) DO NOTHING;

-- Insertar apariciones iniciales
INSERT INTO content_manager_quiroz_apariciones (medio, fecha, tema, sentimiento) VALUES
('El Tiempo', '02 Junio 2024', 'Garantías para el proceso de inscripción de cédulas', 'positivo'),
('Revista Semana', '01 Junio 2024', 'Respuesta a cuestionamientos sobre el software electoral', 'neutral'),
('La FM', '31 Mayo 2024', 'Entrevista sobre transparencia en las mesas de votación', 'positivo'),
('Noticias RCN', '30 Mayo 2024', 'Balance de la jornada de registro de testigos', 'positivo'),
('Blu Radio', '29 Mayo 2024', 'Aclaración sobre la base de datos de la Registraduría', 'negativo');
