-- ============================================================
-- CNE Colombia · Conversación Nacional (multiplataforma por departamento)
-- Tabla análoga a content_manager_mapa_countries pero a nivel departamental,
-- con volúmenes por plataforma (TikTok, X, Instagram, Facebook).
-- Los valores de "nombre" coinciden (tras normalizar acentos/mayúsculas) con
-- la propiedad NOMBRE_DPT del GeoJSON public/colombia-departamentos.geojson.
-- Pantalla: /nacional (modo CNE).
-- ============================================================

CREATE TABLE IF NOT EXISTS content_manager_nacional_departamentos (
    id                   TEXT PRIMARY KEY,        -- Código DANE del departamento
    nombre               TEXT NOT NULL,           -- Nombre (match con NOMBRE_DPT del GeoJSON)
    capital              TEXT,
    lat                  NUMERIC,
    lng                  NUMERIC,
    tema                 TEXT,
    keywords             JSONB DEFAULT '[]'::jsonb,
    sentimiento          TEXT,
    sentimiento_pct      JSONB,                   -- {positivo, neutral, negativo}
    volumen              NUMERIC DEFAULT 0,       -- Menciones totales (suma de plataformas)
    plataforma_dominante TEXT,
    plataformas          JSONB,                   -- {"TikTok": n, "X": n, "Instagram": n, "Facebook": n}
    resumen              TEXT,
    tendencia            TEXT,                    -- 'sube' | 'estable' | 'baja'
    pct_cambio           NUMERIC DEFAULT 0,
    top_hashtags         JSONB DEFAULT '[]'::jsonb,
    update_time          TEXT
);

-- ---------- Seguridad (RLS) coherente con el resto del proyecto ----------
ALTER TABLE content_manager_nacional_departamentos ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Lectura abierta para autenticados" ON content_manager_nacional_departamentos;
CREATE POLICY "Lectura abierta para autenticados"
    ON content_manager_nacional_departamentos FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "Escritura solo para admins" ON content_manager_nacional_departamentos;
CREATE POLICY "Escritura solo para admins"
    ON content_manager_nacional_departamentos FOR ALL TO authenticated
    USING (public.is_admin()) WITH CHECK (public.is_admin());

-- ---------- Datos semilla (33 departamentos) ----------
INSERT INTO content_manager_nacional_departamentos
(id, nombre, capital, lat, lng, tema, keywords, sentimiento, sentimiento_pct, volumen, plataforma_dominante, plataformas, resumen, tendencia, pct_cambio, top_hashtags, update_time)
VALUES
('05', 'Antioquia', 'Medellín', 7.001, -75.836, 'Cobertura de campañas y candidatos en redes', '["Elecciones2026","CNE","Antioquia","VotoColombia"]', 'neutral', '{"positivo":45,"neutral":54,"negativo":1}', 31796, 'TikTok', '{"TikTok":10934,"X":9286,"Instagram":8497,"Facebook":3079}', 'Conversación nacional en Antioquia sobre el proceso electoral 2026, distribuida entre TikTok, X, Instagram y Facebook. Capital: Medellín.', 'sube', 8.9, '["#Elecciones2026","#CNEColombia","#Antioquia"]', 'hace 3 min'),
('08', 'Atlántico', 'Barranquilla', 10.675, -74.973, 'Conversación sobre cédula y puestos de votación', '["Elecciones2026","CNE","Atlántico","VotoColombia"]', 'positivo', '{"positivo":41,"neutral":32,"negativo":27}', 14624, 'TikTok', '{"TikTok":5914,"X":4212,"Instagram":2962,"Facebook":1536}', 'Conversación nacional en Atlántico sobre el proceso electoral 2026, distribuida entre TikTok, X, Instagram y Facebook. Capital: Barranquilla.', 'baja', -2.7, '["#Elecciones2026","#CNEColombia","#Atlántico"]', 'hace 4 min'),
('11', 'Santafé de Bogotá D.C', 'Bogotá', 4.286, -74.211, 'Debates y propuestas electorales', '["Elecciones2026","CNE","Santafé","VotoColombia"]', 'neutral', '{"positivo":37,"neutral":38,"negativo":25}', 45453, 'TikTok', '{"TikTok":12953,"X":12911,"Instagram":12630,"Facebook":6959}', 'Conversación nacional en Santafé de Bogotá D.C sobre el proceso electoral 2026, distribuida entre TikTok, X, Instagram y Facebook. Capital: Bogotá.', 'baja', 9.7, '["#Elecciones2026","#CNEColombia","#SantafédeBogotáDC"]', 'hace 5 min'),
('13', 'Bolívar', 'Cartagena', 9.125, -74.764, 'Pedagogía electoral del CNE', '["Elecciones2026","CNE","Bolívar","VotoColombia"]', 'neutral', '{"positivo":33,"neutral":45,"negativo":22}', 28281, 'TikTok', '{"TikTok":9772,"X":7920,"Instagram":6029,"Facebook":4560}', 'Conversación nacional en Bolívar sobre el proceso electoral 2026, distribuida entre TikTok, X, Instagram y Facebook. Capital: Cartagena.', 'baja', -1.8, '["#Elecciones2026","#CNEColombia","#Bolívar"]', 'hace 6 min'),
('15', 'Boyacá', 'Tunja', 5.849, -73.295, 'Conversación sobre testigos electorales', '["Elecciones2026","CNE","Boyacá","VotoColombia"]', 'positivo', '{"positivo":73,"neutral":20,"negativo":7}', 11109, 'TikTok', '{"TikTok":4511,"X":3067,"Instagram":3205,"Facebook":326}', 'Conversación nacional en Boyacá sobre el proceso electoral 2026, distribuida entre TikTok, X, Instagram y Facebook. Capital: Tunja.', 'estable', 10.6, '["#Elecciones2026","#CNEColombia","#Boyacá"]', 'hace 7 min'),
('17', 'Caldas', 'Manizales', 5.351, -75.38, 'Cobertura de campañas y candidatos en redes', '["Elecciones2026","CNE","Caldas","VotoColombia"]', 'positivo', '{"positivo":69,"neutral":25,"negativo":6}', 41937, 'TikTok', '{"TikTok":12021,"X":11410,"Instagram":9386,"Facebook":9120}', 'Conversación nacional en Caldas sobre el proceso electoral 2026, distribuida entre TikTok, X, Instagram y Facebook. Capital: Manizales.', 'estable', -1.0, '["#Elecciones2026","#CNEColombia","#Caldas"]', 'hace 8 min'),
('18', 'Caquetá', 'Florencia', 0.667, -73.81, 'Conversación sobre cédula y puestos de votación', '["Elecciones2026","CNE","Caquetá","VotoColombia"]', 'positivo', '{"positivo":65,"neutral":31,"negativo":4}', 24765, 'TikTok', '{"TikTok":8598,"X":6639,"Instagram":7408,"Facebook":2120}', 'Conversación nacional en Caquetá sobre el proceso electoral 2026, distribuida entre TikTok, X, Instagram y Facebook. Capital: Florencia.', 'estable', 11.4, '["#Elecciones2026","#CNEColombia","#Caquetá"]', 'hace 9 min'),
('19', 'Cauca', 'Popayán', 2.324, -76.835, 'Debates y propuestas electorales', '["Elecciones2026","CNE","Cauca","VotoColombia"]', 'positivo', '{"positivo":61,"neutral":37,"negativo":2}', 55593, 'TikTok', '{"TikTok":22668,"X":14681,"Instagram":13034,"Facebook":5210}', 'Conversación nacional en Cauca sobre el proceso electoral 2026, distribuida entre TikTok, X, Instagram y Facebook. Capital: Popayán.', 'sube', -0.2, '["#Elecciones2026","#CNEColombia","#Cauca"]', 'hace 10 min'),
('20', 'Cesar', 'Valledupar', 9.29, -73.524, 'Pedagogía electoral del CNE', '["Elecciones2026","CNE","Cesar","VotoColombia"]', 'positivo', '{"positivo":57,"neutral":22,"negativo":21}', 38421, 'TikTok', '{"TikTok":11077,"X":9993,"Instagram":6523,"Facebook":10828}', 'Conversación nacional en Cesar sobre el proceso electoral 2026, distribuida entre TikTok, X, Instagram y Facebook. Capital: Valledupar.', 'sube', 12.2, '["#Elecciones2026","#CNEColombia","#Cesar"]', 'hace 11 min'),
('23', 'Córdoba', 'Montería', 8.531, -75.697, 'Conversación sobre testigos electorales', '["Elecciones2026","CNE","Córdoba","VotoColombia"]', 'positivo', '{"positivo":52,"neutral":28,"negativo":20}', 21249, 'TikTok', '{"TikTok":7413,"X":5442,"Instagram":5208,"Facebook":3186}', 'Conversación nacional en Córdoba sobre el proceso electoral 2026, distribuida entre TikTok, X, Instagram y Facebook. Capital: Montería.', 'baja', 0.7, '["#Elecciones2026","#CNEColombia","#Córdoba"]', 'hace 3 min'),
('25', 'Cundinamarca', 'Bogotá', 4.755, -74.174, 'Cobertura de campañas y candidatos en redes', '["Elecciones2026","CNE","Cundinamarca","VotoColombia"]', 'positivo', '{"positivo":48,"neutral":34,"negativo":18}', 52077, 'TikTok', '{"TikTok":21320,"X":13129,"Instagram":9395,"Facebook":8233}', 'Conversación nacional en Cundinamarca sobre el proceso electoral 2026, distribuida entre TikTok, X, Instagram y Facebook. Capital: Bogotá.', 'baja', 13.1, '["#Elecciones2026","#CNEColombia","#Cundinamarca"]', 'hace 4 min'),
('27', 'Chocó', 'Quibdó', 6.016, -77.004, 'Conversación sobre cédula y puestos de votación', '["Elecciones2026","CNE","Chocó","VotoColombia"]', 'positivo', '{"positivo":44,"neutral":40,"negativo":16}', 34906, 'TikTok', '{"TikTok":10121,"X":8661,"Instagram":8926,"Facebook":7198}', 'Conversación nacional en Chocó sobre el proceso electoral 2026, distribuida entre TikTok, X, Instagram y Facebook. Capital: Quibdó.', 'baja', 1.5, '["#Elecciones2026","#CNEColombia","#Chocó"]', 'hace 5 min'),
('41', 'Huila', 'Neiva', 2.665, -75.602, 'Debates y propuestas electorales', '["Elecciones2026","CNE","Huila","VotoColombia"]', 'neutral', '{"positivo":40,"neutral":47,"negativo":13}', 17734, 'TikTok', '{"TikTok":6216,"X":4329,"Instagram":3388,"Facebook":3801}', 'Conversación nacional en Huila sobre el proceso electoral 2026, distribuida entre TikTok, X, Instagram y Facebook. Capital: Neiva.', 'estable', 13.9, '["#Elecciones2026","#CNEColombia","#Huila"]', 'hace 6 min'),
('44', 'La Guajira', 'Riohacha', 11.452, -72.493, 'Pedagogía electoral del CNE', '["Elecciones2026","CNE","La","VotoColombia"]', 'neutral', '{"positivo":36,"neutral":54,"negativo":10}', 48562, 'TikTok', '{"TikTok":19962,"X":11661,"Instagram":12935,"Facebook":4004}', 'Conversación nacional en La Guajira sobre el proceso electoral 2026, distribuida entre TikTok, X, Instagram y Facebook. Capital: Riohacha.', 'estable', 2.3, '["#Elecciones2026","#CNEColombia","#LaGuajira"]', 'hace 7 min'),
('47', 'Magdalena', 'Santa Marta', 10.189, -74.265, 'Conversación sobre testigos electorales', '["Elecciones2026","CNE","Magdalena","VotoColombia"]', 'neutral', '{"positivo":31,"neutral":63,"negativo":6}', 31390, 'TikTok', '{"TikTok":9154,"X":7412,"Instagram":6331,"Facebook":8493}', 'Conversación nacional en Magdalena sobre el proceso electoral 2026, distribuida entre TikTok, X, Instagram y Facebook. Capital: Santa Marta.', 'sube', 14.7, '["#Elecciones2026","#CNEColombia","#Magdalena"]', 'hace 8 min'),
('50', 'Meta', 'Villavicencio', 3.218, -73.111, 'Cobertura de campañas y candidatos en redes', '["Elecciones2026","CNE","Meta","VotoColombia"]', 'positivo', '{"positivo":72,"neutral":28,"negativo":0}', 14218, 'TikTok', '{"TikTok":5007,"X":3300,"Instagram":3938,"Facebook":1973}', 'Conversación nacional en Meta sobre el proceso electoral 2026, distribuida entre TikTok, X, Instagram y Facebook. Capital: Villavicencio.', 'sube', 3.2, '["#Elecciones2026","#CNEColombia","#Meta"]', 'hace 9 min'),
('52', 'Nariño', 'Pasto', 1.574, -77.822, 'Conversación sobre cédula y puestos de votación', '["Elecciones2026","CNE","Nariño","VotoColombia"]', 'positivo', '{"positivo":68,"neutral":18,"negativo":14}', 45046, 'TikTok', '{"TikTok":18591,"X":10277,"Instagram":9564,"Facebook":6614}', 'Conversación nacional en Nariño sobre el proceso electoral 2026, distribuida entre TikTok, X, Instagram y Facebook. Capital: Pasto.', 'sube', 15.6, '["#Elecciones2026","#CNEColombia","#Nariño"]', 'hace 10 min'),
('54', 'Norte de Santander', 'Cúcuta', 7.871, -72.949, 'Debates y propuestas electorales', '["Elecciones2026","CNE","Norte","VotoColombia"]', 'positivo', '{"positivo":64,"neutral":22,"negativo":14}', 27874, 'TikTok', '{"TikTok":8175,"X":6248,"Instagram":8017,"Facebook":5434}', 'Conversación nacional en Norte de Santander sobre el proceso electoral 2026, distribuida entre TikTok, X, Instagram y Facebook. Capital: Cúcuta.', 'baja', 4.0, '["#Elecciones2026","#CNEColombia","#NortedeSantander"]', 'hace 11 min'),
('63', 'Quindío', 'Armenia', 4.498, -75.702, 'Pedagogía electoral del CNE', '["Elecciones2026","CNE","Quindío","VotoColombia"]', 'positivo', '{"positivo":60,"neutral":27,"negativo":13}', 10702, 'TikTok', '{"TikTok":3787,"X":2356,"Instagram":2386,"Facebook":2173}', 'Conversación nacional en Quindío sobre el proceso electoral 2026, distribuida entre TikTok, X, Instagram y Facebook. Capital: Armenia.', 'baja', 16.4, '["#Elecciones2026","#CNEColombia","#Quindío"]', 'hace 3 min'),
('66', 'Risaralda', 'Pereira', 5.061, -75.893, 'Conversación sobre testigos electorales', '["Elecciones2026","CNE","Risaralda","VotoColombia"]', 'positivo', '{"positivo":56,"neutral":33,"negativo":11}', 41531, 'TikTok', '{"TikTok":17210,"X":8977,"Instagram":12387,"Facebook":2957}', 'Conversación nacional en Risaralda sobre el proceso electoral 2026, distribuida entre TikTok, X, Instagram y Facebook. Capital: Pereira.', 'baja', 4.8, '["#Elecciones2026","#CNEColombia","#Risaralda"]', 'hace 4 min'),
('68', 'Santander', 'Bucaramanga', 6.611, -73.428, 'Cobertura de campañas y candidatos en redes', '["Elecciones2026","CNE","Santander","VotoColombia"]', 'positivo', '{"positivo":51,"neutral":40,"negativo":9}', 24359, 'TikTok', '{"TikTok":7184,"X":5168,"Instagram":5690,"Facebook":6317}', 'Conversación nacional en Santander sobre el proceso electoral 2026, distribuida entre TikTok, X, Instagram y Facebook. Capital: Bucaramanga.', 'estable', 17.2, '["#Elecciones2026","#CNEColombia","#Santander"]', 'hace 5 min'),
('70', 'Sucre', 'Sincelejo', 9.135, -75.206, 'Conversación sobre cédula y puestos de votación', '["Elecciones2026","CNE","Sucre","VotoColombia"]', 'positivo', '{"positivo":47,"neutral":47,"negativo":6}', 55187, 'TikTok', '{"TikTok":19618,"X":11488,"Instagram":9321,"Facebook":14760}', 'Conversación nacional en Sucre sobre el proceso electoral 2026, distribuida entre TikTok, X, Instagram y Facebook. Capital: Sincelejo.', 'estable', 5.7, '["#Elecciones2026","#CNEColombia","#Sucre"]', 'hace 6 min'),
('73', 'Tolima', 'Ibagué', 4.076, -75.212, 'Debates y propuestas electorales', '["Elecciones2026","CNE","Tolima","VotoColombia"]', 'neutral', '{"positivo":43,"neutral":54,"negativo":3}', 38015, 'TikTok', '{"TikTok":15816,"X":7762,"Instagram":9284,"Facebook":5153}', 'Conversación nacional en Tolima sobre el proceso electoral 2026, distribuida entre TikTok, X, Instagram y Facebook. Capital: Ibagué.', 'sube', -5.9, '["#Elecciones2026","#CNEColombia","#Tolima"]', 'hace 7 min'),
('76', 'Valle del Cauca', 'Cali', 3.98, -76.566, 'Pedagogía electoral del CNE', '["Elecciones2026","CNE","Valle","VotoColombia"]', 'positivo', '{"positivo":39,"neutral":32,"negativo":29}', 20843, 'Facebook', '{"TikTok":6182,"X":4172,"Instagram":3742,"Facebook":6747}', 'Conversación nacional en Valle del Cauca sobre el proceso electoral 2026, distribuida entre TikTok, X, Instagram y Facebook. Capital: Cali.', 'sube', 6.5, '["#Elecciones2026","#CNEColombia","#ValledelCauca"]', 'hace 8 min'),
('81', 'Arauca', 'Arauca', 6.481, -71.18, 'Conversación sobre testigos electorales', '["Elecciones2026","CNE","Arauca","VotoColombia"]', 'neutral', '{"positivo":35,"neutral":38,"negativo":27}', 51671, 'TikTok', '{"TikTok":18454,"X":10137,"Instagram":13169,"Facebook":9911}', 'Conversación nacional en Arauca sobre el proceso electoral 2026, distribuida entre TikTok, X, Instagram y Facebook. Capital: Arauca.', 'sube', -5.1, '["#Elecciones2026","#CNEColombia","#Arauca"]', 'hace 9 min'),
('85', 'Casanare', 'Yopal', 5.445, -71.737, 'Cobertura de campañas y candidatos en redes', '["Elecciones2026","CNE","Casanare","VotoColombia"]', 'neutral', '{"positivo":30,"neutral":46,"negativo":24}', 34499, 'TikTok', '{"TikTok":14410,"X":6631,"Instagram":6561,"Facebook":6897}', 'Conversación nacional en Casanare sobre el proceso electoral 2026, distribuida entre TikTok, X, Instagram y Facebook. Capital: Yopal.', 'baja', 7.3, '["#Elecciones2026","#CNEColombia","#Casanare"]', 'hace 10 min'),
('86', 'Putumayo', 'Mocoa', 0.338, -75.618, 'Conversación sobre cédula y puestos de votación', '["Elecciones2026","CNE","Putumayo","VotoColombia"]', 'positivo', '{"positivo":71,"neutral":21,"negativo":8}', 17327, 'TikTok', '{"TikTok":5168,"X":3261,"Instagram":4600,"Facebook":4298}', 'Conversación nacional en Putumayo sobre el proceso electoral 2026, distribuida entre TikTok, X, Instagram y Facebook. Capital: Mocoa.', 'baja', -4.3, '["#Elecciones2026","#CNEColombia","#Putumayo"]', 'hace 11 min'),
('88', 'Archipiélago de San Andrés Providencia y Santa Catalina', 'San Andrés', 13.017, -81.523, 'Debates y propuestas electorales', '["Elecciones2026","CNE","Archipiélago","VotoColombia"]', 'positivo', '{"positivo":67,"neutral":26,"negativo":7}', 48155, 'TikTok', '{"TikTok":17278,"X":8871,"Instagram":9670,"Facebook":12336}', 'Conversación nacional en Archipiélago de San Andrés Providencia y Santa Catalina sobre el proceso electoral 2026, distribuida entre TikTok, X, Instagram y Facebook. Capital: San Andrés.', 'estable', 8.1, '["#Elecciones2026","#CNEColombia","#ArchipiélagodeSanAndrésProvidenciaySantaCatalina"]', 'hace 3 min'),
('91', 'Amazonas', 'Leticia', -1.442, -71.734, 'Pedagogía electoral del CNE', '["Elecciones2026","CNE","Amazonas","VotoColombia"]', 'positivo', '{"positivo":63,"neutral":32,"negativo":5}', 30984, 'TikTok', '{"TikTok":12993,"X":5584,"Instagram":8555,"Facebook":3852}', 'Conversación nacional en Amazonas sobre el proceso electoral 2026, distribuida entre TikTok, X, Instagram y Facebook. Capital: Leticia.', 'estable', -3.4, '["#Elecciones2026","#CNEColombia","#Amazonas"]', 'hace 4 min'),
('94', 'Guainía', 'Inírida', 2.831, -68.86, 'Conversación sobre testigos electorales', '["Elecciones2026","CNE","Guainía","VotoColombia"]', 'positivo', '{"positivo":59,"neutral":38,"negativo":3}', 13812, 'X', '{"TikTok":4142,"X":4368,"Instagram":2920,"Facebook":2382}', 'Conversación nacional en Guainía sobre el proceso electoral 2026, distribuida entre TikTok, X, Instagram y Facebook. Capital: Inírida.', 'estable', 9.0, '["#Elecciones2026","#CNEColombia","#Guainía"]', 'hace 5 min'),
('95', 'Guaviare', 'San José del Guaviare', 1.914, -71.868, 'Cobertura de campañas y candidatos en redes', '["Elecciones2026","CNE","Guaviare","VotoColombia"]', 'positivo', '{"positivo":54,"neutral":45,"negativo":1}', 44640, 'TikTok', '{"TikTok":16091,"X":13938,"Instagram":12801,"Facebook":1810}', 'Conversación nacional en Guaviare sobre el proceso electoral 2026, distribuida entre TikTok, X, Instagram y Facebook. Capital: San José del Guaviare.', 'sube', -2.6, '["#Elecciones2026","#CNEColombia","#Guaviare"]', 'hace 6 min'),
('97', 'Vaupés', 'Mitú', 0.321, -70.573, 'Conversación sobre cédula y puestos de votación', '["Elecciones2026","CNE","Vaupés","VotoColombia"]', 'positivo', '{"positivo":50,"neutral":28,"negativo":22}', 27468, 'TikTok', '{"TikTok":11564,"X":8467,"Instagram":6100,"Facebook":1337}', 'Conversación nacional en Vaupés sobre el proceso electoral 2026, distribuida entre TikTok, X, Instagram y Facebook. Capital: Mitú.', 'sube', 9.8, '["#Elecciones2026","#CNEColombia","#Vaupés"]', 'hace 7 min'),
('99', 'Vichada', 'Puerto Carreño', 4.252, -69.261, 'Debates y propuestas electorales', '["Elecciones2026","CNE","Vichada","VotoColombia"]', 'positivo', '{"positivo":46,"neutral":34,"negativo":20}', 10296, 'X', '{"TikTok":3105,"X":3132,"Instagram":3062,"Facebook":997}', 'Conversación nacional en Vichada sobre el proceso electoral 2026, distribuida entre TikTok, X, Instagram y Facebook. Capital: Puerto Carreño.', 'sube', -1.8, '["#Elecciones2026","#CNEColombia","#Vichada"]', 'hace 8 min')
ON CONFLICT (id) DO NOTHING;

-- ---------- Realtime: actualización automática del mapa ----------
-- Habilita la replicación para que /nacional se refresque en vivo al entrar datos.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_publication_tables
        WHERE pubname = 'supabase_realtime' AND schemaname = 'public'
          AND tablename = 'content_manager_nacional_departamentos'
    ) THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.content_manager_nacional_departamentos;
    END IF;
END $$;
