-- Tabla para los KPIs de Elecciones
CREATE TABLE IF NOT EXISTS content_manager_elecciones_kpis (
    id TEXT PRIMARY KEY, -- 'potencial', 'mesas', 'candidatos', 'dias'
    label TEXT NOT NULL,
    value TEXT NOT NULL,
    delta TEXT,
    progress INTEGER DEFAULT 70
);

-- Tabla para Calendario Electoral
CREATE TABLE IF NOT EXISTS content_manager_elecciones_calendario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha TEXT NOT NULL,
    evento TEXT NOT NULL,
    estado TEXT DEFAULT 'pendiente' -- 'completado', 'activo', 'pendiente'
);

-- Tabla para la estrategia de Elecciones
CREATE TABLE IF NOT EXISTS content_manager_elecciones_strategy (
    id TEXT PRIMARY KEY, -- 'main'
    narrativa JSONB DEFAULT '{}',
    pilares JSONB DEFAULT '[]',
    noticias JSONB DEFAULT '[]',
    contenido JSONB DEFAULT '{}',
    conversacion JSONB DEFAULT '{}',
    pauta JSONB DEFAULT '[]'
);

-- Tabla para Participación Histórica
CREATE TABLE IF NOT EXISTS content_manager_elecciones_participacion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    anio TEXT NOT NULL,
    pct FLOAT NOT NULL
);

-- Insertar Participación inicial
INSERT INTO content_manager_elecciones_participacion (anio, pct) VALUES
('2006', 45.1),
('2010', 49.3),
('2014', 47.9),
('2018', 53.0),
('2022', 58.1),
('2026', 61.2)
ON CONFLICT DO NOTHING;

-- Insertar KPIs iniciales
INSERT INTO content_manager_elecciones_kpis (id, label, value, delta, progress) VALUES
('potencial', 'Potencial Electoral', '38.8M', '+2.4%', 70),
('mesas', 'Mesas Habilitadas', '115,432', '+1.1%', 70),
('candidatos', 'Candidatos Presidenciales', '18', '+3', 70),
('dias', 'Días para Elección', '247', NULL, 70)
ON CONFLICT (id) DO NOTHING;

-- Insertar Calendario inicial
INSERT INTO content_manager_elecciones_calendario (fecha, evento, estado) VALUES
('Ene 2026', 'Cierre inscripción candidatos', 'completado'),
('Feb 2026', 'Inicio campaña electoral', 'completado'),
('Mar 2026', 'Debate presidencial CNE', 'activo'),
('Abr 2026', 'Auditorías software votación', 'pendiente'),
('25 May 2026', 'Jornada electoral 1ra vuelta', 'pendiente'),
('Jun 2026', '2da vuelta (si aplica)', 'pendiente')
ON CONFLICT DO NOTHING;

-- Insertar Estrategia inicial (basada en mock)
INSERT INTO content_manager_elecciones_strategy (id, narrativa, pilares, noticias, contenido, conversacion, pauta) VALUES
('main', 
 '{"gancho": "El futuro de Colombia se decide en las urnas con plenas garantías.", "tipoConversacion": "Debate Democrático", "mensajeClave": "Tu voto es libre, secreto y está protegido.", "arco": [{"fase": "Inscripción", "tipo": "informativo", "mensaje": "Apertura de puestos de votación."}, {"fase": "Campaña", "tipo": "accion", "mensaje": "Control de publicidad electoral."}, {"fase": "Elección", "tipo": "resultado", "mensaje": "Jornada electoral pacífica."}, {"fase": "Escrutinio", "tipo": "confianza", "mensaje": "Resultados oficiales rápidos y seguros."}]}',
 '[{"pilar": "Garantías Electorales", "icono": "⚖️", "color": "#2b82ee", "descripcion": "Igualdad de condiciones para todos los candidatos."}, {"pilar": "Participación Masiva", "icono": "🗳️", "color": "#f3b116", "descripcion": "Fomento del voto joven y rural."}, {"pilar": "Innovación Técnica", "icono": "⚡", "color": "#2eb88a", "descripcion": "Software de última generación para el conteo."}]',
 '[{"medio": "El Tiempo", "titulo": "CNE confirma 18 candidatos para la presidencia 2026", "fecha": "Hace 2d", "categoria": "Política", "url": "#"}, {"medio": "Semana", "titulo": "Así va el mapa de puestos de votación en zonas de conflicto", "fecha": "Hace 4h", "categoria": "Seguridad", "url": "#"}]',
 '{"instagram": [{"formato": "Reel", "idea": "Cómo marcar el tarjetón correctamente", "tipo": "Pedagogía"}], "facebook": [{"formato": "Infografía", "idea": "Puestos de votación en el exterior", "tipo": "Informativo"}], "x": [{"formato": "Hilo", "idea": "Cronograma de debates presidenciales", "tipo": "Actualidad"}], "tiktok": [{"formato": "Video", "idea": "Mitos sobre el voto en blanco", "tipo": "Claridad"}]}',
 '{"instagram": {"menciones": 28400, "sentimiento": 68, "volumePeak": "Viernes 19:00", "topHashtags": ["#Elecciones2026", "#VotoColombia"]}, "facebook": {"menciones": 41200, "sentimiento": 62, "volumePeak": "Miércoles 13:00", "topHashtags": ["#ColombiaVota", "#Presidenciales"]}, "x": {"menciones": 89700, "sentimiento": 54, "volumePeak": "Lunes 10:00", "topHashtags": ["#Elecciones2026", "#CNE"]}, "tiktok": {"menciones": 156000, "sentimiento": 71, "volumePeak": "Sábado 21:00", "topHashtags": ["#Votemos", "#25Mayo"]}}',
 '[{"formato": "Video", "objetivo": "Awareness", "presupuesto": "Muy Alto", "cta": "Vota este 25 de mayo", "segmento": "Población General", "plataforma": ["TV", "Redes Sociales"]}]'
) ON CONFLICT (id) DO NOTHING;
