-- Tabla para KPIs de Testigos
CREATE TABLE IF NOT EXISTS content_manager_testigos_kpis (
    id TEXT PRIMARY KEY, -- 'asignados', 'acreditados', 'misiones', 'deptos'
    label TEXT NOT NULL,
    value TEXT DEFAULT '0',
    delta TEXT DEFAULT NULL,
    progress INTEGER DEFAULT 70
);

-- Tabla para Testigos por Departamento
CREATE TABLE IF NOT EXISTS content_manager_testigos_deptos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    depto TEXT NOT NULL,
    count INTEGER DEFAULT 0
);

-- Tabla para Misiones / Globe Markers
CREATE TABLE IF NOT EXISTS content_manager_testigos_misiones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pais TEXT NOT NULL,
    ciudad TEXT NOT NULL,
    lat FLOAT DEFAULT 0,
    lng FLOAT DEFAULT 0,
    count INTEGER DEFAULT 0,
    tipo TEXT NOT NULL,
    narrativa TEXT DEFAULT '',
    tendencia TEXT DEFAULT ''
);

-- Tabla para Estrategia de Testigos
CREATE TABLE IF NOT EXISTS content_manager_testigos_strategy (
    id TEXT PRIMARY KEY, -- 'main'
    narrativa JSONB DEFAULT '{}',
    pilares JSONB DEFAULT '[]',
    noticias JSONB DEFAULT '[]',
    contenido JSONB DEFAULT '{}',
    conversacion JSONB DEFAULT '{}',
    pauta JSONB DEFAULT '[]'
);

-- Insertar KPIs iniciales
INSERT INTO content_manager_testigos_kpis (id, label, value, delta, progress) VALUES
('asignados', 'Total Asignados', '142.800', NULL, 70),
('acreditados', 'Acreditados', '98.430', '+69%', 70),
('misiones', 'Misiones Internacionales', '12', NULL, 70),
('deptos', 'Dpto. Cubiertos', '32', NULL, 70)
ON CONFLICT (id) DO NOTHING;

-- Insertar Departamentos iniciales
INSERT INTO content_manager_testigos_deptos (depto, count) VALUES
('Bogotá', 28000),
('Antioquia', 22000),
('Valle', 18500),
('Atlántico', 12000),
('Cundinamarca', 9800),
('Otros', 8130)
ON CONFLICT DO NOTHING;

-- Insertar Misiones iniciales
INSERT INTO content_manager_testigos_misiones (pais, ciudad, lat, lng, count, tipo, narrativa, tendencia) VALUES
('México', 'Ciudad de México', 19.4, -99.1, 3, 'Misión OEA', 'Interés creciente en modelo electoral colombiano', 'Positiva ↑'),
('Argentina', 'Buenos Aires', -34.6, -58.4, 5, 'Observadores UNASUR', 'Solidez institucional del CNE es referente regional', 'Positiva ↑'),
('España', 'Madrid', 40.4, -3.7, 8, 'Misión UE', 'Colombia consolida democracia de calidad en Latam', 'Muy positiva ↑↑'),
('Estados Unidos', 'Washington D.C.', 38.9, -77, 12, 'Carter Center', 'Proceso técnico sólido, seguimiento del software electoral', 'Positiva ↑'),
('Brasil', 'Brasilia', -15.8, -47.9, 4, 'UNASUR', 'Experiencia colombiana aporta a la integración electoral regional', 'Neutral →'),
('Francia', 'París', 48.9, 2.3, 6, 'Misión UE', 'Estándares europeos aplicados al contexto colombiano', 'Positiva ↑'),
('Venezuela', 'Caracas', 10.5, -66.9, 2, 'UNASUR', 'Contraste con proceso interno genera atención al modelo CNE', 'Mixta ↔'),
('Chile', 'Santiago', -33.5, -70.6, 3, 'UNIORE', 'Referente de transparencia para sistemas postransición', 'Positiva ↑'),
('Perú', 'Lima', -12, -77, 4, 'UNIORE', 'Benchmarking técnico con proceso colombiano', 'Neutral →'),
('Alemania', 'Berlín', 52.5, 13.4, 5, 'Misión UE', 'Monitoreo de estándares democráticos OCDE en Colombia', 'Positiva ↑'),
('Japón', 'Tokio', 35.7, 139.7, 2, 'Observadores', 'Interés técnico en sistemas de votación electrónica', 'Neutral →'),
('Canadá', 'Ottawa', 45.4, -75.7, 3, 'Carter Center', 'Énfasis en participación de minorías y zonas rurales', 'Positiva ↑')
ON CONFLICT DO NOTHING;

-- Insertar Estrategia inicial (basada en mock)
INSERT INTO content_manager_testigos_strategy (id, narrativa, pilares, noticias, contenido, conversacion, pauta) VALUES
('main', 
 '{"gancho": "La red de testigos más grande de la historia blindará las elecciones 2026.", "tipoConversacion": "Participación + Vigilancia", "mensajeClave": "Tu voto está protegido por miles de ciudadanos.", "arco": [{"fase": "Convocatoria", "tipo": "informativo", "mensaje": "Invitación masiva a la ciudadanía."}, {"fase": "Inscripción", "tipo": "accion", "mensaje": "Meta de 150.000 testigos superada."}, {"fase": "Capacitación", "tipo": "educacion", "mensaje": "Talleres técnicos en todo el país."}, {"fase": "Despliegue", "tipo": "resultado", "mensaje": "Cobertura total en el 100% de las mesas."}]}',
 '[{"pilar": "Vigilancia Ciudadana", "icono": "👥", "color": "#2b82ee", "descripcion": "Empoderamiento del ciudadano como garante del proceso."}, {"pilar": "Capacitación Técnica", "icono": "📚", "color": "#f3b116", "descripcion": "Formación rigurosa en normatividad y software."}, {"pilar": "Cobertura Nacional", "icono": "📍", "color": "#2eb88a", "descripcion": "Presencia efectiva en los 32 departamentos."}]',
 '[{"medio": "El Tiempo", "titulo": "CNE abre inscripciones para testigos electorales 2026", "fecha": "Hace 1d", "categoria": "Convocatoria", "url": "#"}, {"medio": "W Radio", "titulo": "Misiones internacionales avalan plan de testigos del CNE", "fecha": "Hace 5h", "categoria": "Internacional", "url": "#"}]',
 '{"instagram": [{"formato": "Reel", "idea": "POV: Mi día como testigo electoral", "tipo": "Inspiracional"}], "facebook": [{"formato": "Post", "idea": "Guía paso a paso para inscribirte", "tipo": "Informativo"}], "x": [{"formato": "Hilo", "idea": "Por qué los testigos son la base de la confianza", "tipo": "Pedagogía"}], "tiktok": [{"formato": "Tutorial", "idea": "Cómo usar la app de testigos", "tipo": "Técnico"}]}',
 '{"instagram": {"menciones": 3200, "sentimiento": 78, "volumePeak": "Lunes 18:00", "topHashtags": ["#TestigosElectorales", "#VotoSeguro"]}, "facebook": {"menciones": 4500, "sentimiento": 72, "volumePeak": "Martes 10:00", "topHashtags": ["#Democracia", "#CNE"]}, "x": {"menciones": 12000, "sentimiento": 65, "volumePeak": "Jueves 09:00", "topHashtags": ["#VigilanciaCiudadana"]}, "tiktok": {"menciones": 8500, "sentimiento": 82, "volumePeak": "Viernes 20:00", "topHashtags": ["#SoyTestigo"]}}',
 '[{"formato": "Story", "objetivo": "Conversión", "presupuesto": "Alto", "cta": "Inscríbete aquí", "segmento": "Jóvenes 18-35", "plataforma": ["Instagram", "Facebook"]}]'
) ON CONFLICT (id) DO NOTHING;
