-- ============================================================
-- Actores Electorales · Mapa de Colombia (Instagram por departamento)
-- Tabla analoga a content_manager_mapa_countries pero a nivel departamental.
-- Los valores de "nombre" coinciden (tras normalizar acentos/mayusculas) con
-- la propiedad NOMBRE_DPT del GeoJSON public/colombia-departamentos.geojson.
-- ============================================================

CREATE TABLE IF NOT EXISTS content_manager_actores_colombia (
    id              TEXT PRIMARY KEY,        -- Codigo DANE del departamento
    nombre          TEXT NOT NULL,           -- Nombre (match con NOMBRE_DPT del GeoJSON)
    capital         TEXT,
    lat             NUMERIC,
    lng             NUMERIC,
    tema            TEXT,
    keywords        JSONB DEFAULT '[]'::jsonb,
    sentimiento     TEXT,
    sentimiento_pct JSONB,                    -- {positivo, neutral, negativo}
    volumen         NUMERIC DEFAULT 0,        -- Menciones en Instagram
    plataformas     JSONB,                    -- {"Instagram": n}
    resumen         TEXT,
    tendencia       TEXT,                     -- 'sube' | 'estable' | 'baja'
    pct_cambio      NUMERIC DEFAULT 0,
    top_hashtags    JSONB DEFAULT '[]'::jsonb,
    update_time     TEXT
);

-- ---------- Seguridad (RLS) coherente con el resto del proyecto ----------
ALTER TABLE content_manager_actores_colombia ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Lectura abierta para autenticados" ON content_manager_actores_colombia;
CREATE POLICY "Lectura abierta para autenticados"
    ON content_manager_actores_colombia FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "Escritura solo para admins" ON content_manager_actores_colombia;
CREATE POLICY "Escritura solo para admins"
    ON content_manager_actores_colombia FOR ALL TO authenticated
    USING (public.is_admin()) WITH CHECK (public.is_admin());

-- ---------- Datos semilla (33 departamentos) ----------
INSERT INTO content_manager_actores_colombia
(id, nombre, capital, lat, lng, tema, keywords, sentimiento, sentimiento_pct, volumen, plataformas, resumen, tendencia, pct_cambio, top_hashtags, update_time)
VALUES
('05', 'Antioquia', 'Medellín', 7.001, -75.836, 'Cobertura de campañas y candidatos en Instagram', '["Elecciones2026","CNE","Instagram","Antioquia"]', 'neutral', '{"positivo":40,"neutral":52,"negativo":8}', 46160, '{"Instagram":46160}', 'Conversación en Instagram en Antioquia centrada en el proceso electoral 2026. Capital: Medellín.', 'sube', -1.3, '["#Elecciones2026","#CNEColombia","#Antioquia"]', 'hace 3 min'),
('08', 'Atlántico', 'Barranquilla', 10.675, -74.973, 'Reels sobre cédula y puestos de votación', '["Elecciones2026","CNE","Instagram","Atlántico"]', 'neutral', '{"positivo":47,"neutral":42,"negativo":11}', 36500, '{"Instagram":36500}', 'Conversación en Instagram en Atlántico centrada en el proceso electoral 2026. Capital: Barranquilla.', 'estable', 0.8, '["#Elecciones2026","#CNEColombia","#Atlántico"]', 'hace 4 min'),
('11', 'Santafé de Bogotá D.C', 'Bogotá', 4.286, -74.211, 'Debates y propuestas de actores electorales', '["Elecciones2026","CNE","Instagram","Santafé"]', 'neutral', '{"positivo":54,"neutral":32,"negativo":14}', 51800, '{"Instagram":51800}', 'Conversación en Instagram en Santafé de Bogotá D.C centrada en el proceso electoral 2026. Capital: Bogotá.', 'baja', 6, '["#Elecciones2026","#CNEColombia","#SantafédeBogotáDC"]', 'hace 5 min'),
('13', 'Bolívar', 'Cartagena', 9.125, -74.764, 'Pedagogía electoral del CNE en redes', '["Elecciones2026","CNE","Instagram","Bolívar"]', 'positivo', '{"positivo":61,"neutral":22,"negativo":17}', 36380, '{"Instagram":36380}', 'Conversación en Instagram en Bolívar centrada en el proceso electoral 2026. Capital: Cartagena.', 'sube', 7.4, '["#Elecciones2026","#CNEColombia","#Bolívar"]', 'hace 6 min'),
('15', 'Boyacá', 'Tunja', 5.849, -73.295, 'Conversación sobre testigos electorales', '["Elecciones2026","CNE","Instagram","Boyacá"]', 'positivo', '{"positivo":68,"neutral":12,"negativo":20}', 29600, '{"Instagram":29600}', 'Conversación en Instagram en Boyacá centrada en el proceso electoral 2026. Capital: Tunja.', 'estable', 9.8, '["#Elecciones2026","#CNEColombia","#Boyacá"]', 'hace 7 min'),
('17', 'Caldas', 'Manizales', 5.351, -75.38, 'Cobertura de campañas y candidatos en Instagram', '["Elecciones2026","CNE","Instagram","Caldas"]', 'negativo', '{"positivo":40,"neutral":37,"negativo":23}', 24080, '{"Instagram":24080}', 'Conversación en Instagram en Caldas centrada en el proceso electoral 2026. Capital: Manizales.', 'baja', 13, '["#Elecciones2026","#CNEColombia","#Caldas"]', 'hace 8 min'),
('18', 'Caquetá', 'Florencia', 0.667, -73.81, 'Reels sobre cédula y puestos de votación', '["Elecciones2026","CNE","Instagram","Caquetá"]', 'neutral', '{"positivo":47,"neutral":45,"negativo":8}', 17300, '{"Instagram":17300}', 'Conversación en Instagram en Caquetá centrada en el proceso electoral 2026. Capital: Florencia.', 'sube', 15.4, '["#Elecciones2026","#CNEColombia","#Caquetá"]', 'hace 9 min'),
('19', 'Cauca', 'Popayán', 2.324, -76.835, 'Debates y propuestas de actores electorales', '["Elecciones2026","CNE","Instagram","Cauca"]', 'neutral', '{"positivo":54,"neutral":35,"negativo":11}', 28760, '{"Instagram":28760}', 'Conversación en Instagram en Cauca centrada en el proceso electoral 2026. Capital: Popayán.', 'estable', -3.7, '["#Elecciones2026","#CNEColombia","#Cauca"]', 'hace 10 min'),
('20', 'Cesar', 'Valledupar', 9.29, -73.524, 'Pedagogía electoral del CNE en redes', '["Elecciones2026","CNE","Instagram","Cesar"]', 'positivo', '{"positivo":61,"neutral":25,"negativo":14}', 25820, '{"Instagram":25820}', 'Conversación en Instagram en Cesar centrada en el proceso electoral 2026. Capital: Valledupar.', 'baja', -0.8, '["#Elecciones2026","#CNEColombia","#Cesar"]', 'hace 11 min'),
('23', 'Córdoba', 'Montería', 8.531, -75.697, 'Conversación sobre testigos electorales', '["Elecciones2026","CNE","Instagram","Córdoba"]', 'positivo', '{"positivo":68,"neutral":15,"negativo":17}', 28640, '{"Instagram":28640}', 'Conversación en Instagram en Córdoba centrada en el proceso electoral 2026. Capital: Montería.', 'sube', 2.9, '["#Elecciones2026","#CNEColombia","#Córdoba"]', 'hace 3 min'),
('25', 'Cundinamarca', 'Bogotá', 4.755, -74.174, 'Cobertura de campañas y candidatos en Instagram', '["Elecciones2026","CNE","Instagram","Cundinamarca"]', 'neutral', '{"positivo":40,"neutral":40,"negativo":20}', 37520, '{"Instagram":37520}', 'Conversación en Instagram en Cundinamarca centrada en el proceso electoral 2026. Capital: Bogotá.', 'estable', 7.8, '["#Elecciones2026","#CNEColombia","#Cundinamarca"]', 'hace 4 min'),
('27', 'Chocó', 'Quibdó', 6.016, -77.004, 'Reels sobre cédula y puestos de votación', '["Elecciones2026","CNE","Instagram","Chocó"]', 'negativo', '{"positivo":47,"neutral":30,"negativo":23}', 19220, '{"Instagram":19220}', 'Conversación en Instagram en Chocó centrada en el proceso electoral 2026. Capital: Quibdó.', 'baja', 8.8, '["#Elecciones2026","#CNEColombia","#Chocó"]', 'hace 5 min'),
('41', 'Huila', 'Neiva', 2.665, -75.602, 'Debates y propuestas de actores electorales', '["Elecciones2026","CNE","Instagram","Huila"]', 'neutral', '{"positivo":54,"neutral":38,"negativo":8}', 25400, '{"Instagram":25400}', 'Conversación en Instagram en Huila centrada en el proceso electoral 2026. Capital: Neiva.', 'sube', 12.9, '["#Elecciones2026","#CNEColombia","#Huila"]', 'hace 6 min'),
('44', 'La Guajira', 'Riohacha', 11.452, -72.493, 'Pedagogía electoral del CNE en redes', '["Elecciones2026","CNE","Instagram","La"]', 'positivo', '{"positivo":61,"neutral":28,"negativo":11}', 23900, '{"Instagram":23900}', 'Conversación en Instagram en La Guajira centrada en el proceso electoral 2026. Capital: Riohacha.', 'estable', 16, '["#Elecciones2026","#CNEColombia","#LaGuajira"]', 'hace 7 min'),
('47', 'Magdalena', 'Santa Marta', 10.189, -74.265, 'Conversación sobre testigos electorales', '["Elecciones2026","CNE","Instagram","Magdalena"]', 'positivo', '{"positivo":68,"neutral":18,"negativo":14}', 29600, '{"Instagram":29600}', 'Conversación en Instagram en Magdalena centrada en el proceso electoral 2026. Capital: Santa Marta.', 'baja', -3.8, '["#Elecciones2026","#CNEColombia","#Magdalena"]', 'hace 8 min'),
('50', 'Meta', 'Villavicencio', 3.218, -73.111, 'Cobertura de campañas y candidatos en Instagram', '["Elecciones2026","CNE","Instagram","Meta"]', 'neutral', '{"positivo":40,"neutral":43,"negativo":17}', 28400, '{"Instagram":28400}', 'Conversación en Instagram en Meta centrada en el proceso electoral 2026. Capital: Villavicencio.', 'sube', -0.1, '["#Elecciones2026","#CNEColombia","#Meta"]', 'hace 9 min'),
('52', 'Nariño', 'Pasto', 1.574, -77.822, 'Reels sobre cédula y puestos de votación', '["Elecciones2026","CNE","Instagram","Nariño"]', 'neutral', '{"positivo":47,"neutral":33,"negativo":20}', 26900, '{"Instagram":26900}', 'Conversación en Instagram en Nariño centrada en el proceso electoral 2026. Capital: Pasto.', 'estable', 3, '["#Elecciones2026","#CNEColombia","#Nariño"]', 'hace 10 min'),
('54', 'Norte de Santander', 'Cúcuta', 7.871, -72.949, 'Debates y propuestas de actores electorales', '["Elecciones2026","CNE","Instagram","Norte"]', 'negativo', '{"positivo":54,"neutral":23,"negativo":23}', 30680, '{"Instagram":30680}', 'Conversación en Instagram en Norte de Santander centrada en el proceso electoral 2026. Capital: Cúcuta.', 'baja', 6.8, '["#Elecciones2026","#CNEColombia","#NortedeSantander"]', 'hace 11 min'),
('63', 'Quindío', 'Armenia', 4.498, -75.702, 'Pedagogía electoral del CNE en redes', '["Elecciones2026","CNE","Instagram","Quindío"]', 'positivo', '{"positivo":61,"neutral":31,"negativo":8}', 23900, '{"Instagram":23900}', 'Conversación en Instagram en Quindío centrada en el proceso electoral 2026. Capital: Armenia.', 'sube', 9.2, '["#Elecciones2026","#CNEColombia","#Quindío"]', 'hace 3 min'),
('66', 'Risaralda', 'Pereira', 5.061, -75.893, 'Conversación sobre testigos electorales', '["Elecciones2026","CNE","Instagram","Risaralda"]', 'positivo', '{"positivo":68,"neutral":21,"negativo":11}', 29600, '{"Instagram":29600}', 'Conversación en Instagram en Risaralda centrada en el proceso electoral 2026. Capital: Pereira.', 'estable', 13.2, '["#Elecciones2026","#CNEColombia","#Risaralda"]', 'hace 4 min'),
('68', 'Santander', 'Bucaramanga', 6.611, -73.428, 'Cobertura de campañas y candidatos en Instagram', '["Elecciones2026","CNE","Instagram","Santander"]', 'neutral', '{"positivo":40,"neutral":46,"negativo":14}', 34640, '{"Instagram":34640}', 'Conversación en Instagram en Santander centrada en el proceso electoral 2026. Capital: Bucaramanga.', 'baja', 17.7, '["#Elecciones2026","#CNEColombia","#Santander"]', 'hace 5 min'),
('70', 'Sucre', 'Sincelejo', 9.135, -75.206, 'Reels sobre cédula y puestos de votación', '["Elecciones2026","CNE","Instagram","Sucre"]', 'neutral', '{"positivo":47,"neutral":36,"negativo":17}', 20180, '{"Instagram":20180}', 'Conversación en Instagram en Sucre centrada en el proceso electoral 2026. Capital: Sincelejo.', 'sube', -4.6, '["#Elecciones2026","#CNEColombia","#Sucre"]', 'hace 6 min'),
('73', 'Tolima', 'Ibagué', 4.076, -75.212, 'Debates y propuestas de actores electorales', '["Elecciones2026","CNE","Instagram","Tolima"]', 'neutral', '{"positivo":54,"neutral":26,"negativo":20}', 28760, '{"Instagram":28760}', 'Conversación en Instagram en Tolima centrada en el proceso electoral 2026. Capital: Ibagué.', 'estable', -0.3, '["#Elecciones2026","#CNEColombia","#Tolima"]', 'hace 7 min'),
('76', 'Valle del Cauca', 'Cali', 3.98, -76.566, 'Pedagogía electoral del CNE en redes', '["Elecciones2026","CNE","Instagram","Valle"]', 'positivo', '{"positivo":61,"neutral":16,"negativo":23}', 47900, '{"Instagram":47900}', 'Conversación en Instagram en Valle del Cauca centrada en el proceso electoral 2026. Capital: Cali.', 'baja', 5.4, '["#Elecciones2026","#CNEColombia","#ValledelCauca"]', 'hace 8 min'),
('81', 'Arauca', 'Arauca', 6.481, -71.18, 'Conversación sobre testigos electorales', '["Elecciones2026","CNE","Instagram","Arauca"]', 'positivo', '{"positivo":68,"neutral":24,"negativo":8}', 18080, '{"Instagram":18080}', 'Conversación en Instagram en Arauca centrada en el proceso electoral 2026. Capital: Arauca.', 'sube', 5, '["#Elecciones2026","#CNEColombia","#Arauca"]', 'hace 9 min'),
('85', 'Casanare', 'Yopal', 5.445, -71.737, 'Cobertura de campañas y candidatos en Instagram', '["Elecciones2026","CNE","Instagram","Casanare"]', 'neutral', '{"positivo":40,"neutral":49,"negativo":11}', 16400, '{"Instagram":16400}', 'Conversación en Instagram en Casanare centrada en el proceso electoral 2026. Capital: Yopal.', 'estable', 8.6, '["#Elecciones2026","#CNEColombia","#Casanare"]', 'hace 10 min'),
('86', 'Putumayo', 'Mocoa', 0.338, -75.618, 'Reels sobre cédula y puestos de votación', '["Elecciones2026","CNE","Instagram","Putumayo"]', 'neutral', '{"positivo":47,"neutral":39,"negativo":14}', 14420, '{"Instagram":14420}', 'Conversación en Instagram en Putumayo centrada en el proceso electoral 2026. Capital: Mocoa.', 'baja', 11.6, '["#Elecciones2026","#CNEColombia","#Putumayo"]', 'hace 11 min'),
('88', 'Archipiélago de San Andrés Providencia y Santa Catalina', 'San Andrés', 13.017, -81.523, 'Debates y propuestas de actores electorales', '["Elecciones2026","CNE","Instagram","Archipiélago"]', 'neutral', '{"positivo":54,"neutral":29,"negativo":17}', 17240, '{"Instagram":17240}', 'Conversación en Instagram en Archipiélago de San Andrés Providencia y Santa Catalina centrada en el proceso electoral 2026. Capital: San Andrés.', 'sube', 15.3, '["#Elecciones2026","#CNEColombia","#ArchipiélagodeSanAndrésProvidenciaySantaCatalina"]', 'hace 3 min'),
('91', 'Amazonas', 'Leticia', -1.442, -71.734, 'Pedagogía electoral del CNE en redes', '["Elecciones2026","CNE","Instagram","Amazonas"]', 'positivo', '{"positivo":61,"neutral":19,"negativo":20}', 15260, '{"Instagram":15260}', 'Conversación en Instagram en Amazonas centrada en el proceso electoral 2026. Capital: Leticia.', 'estable', -5.5, '["#Elecciones2026","#CNEColombia","#Amazonas"]', 'hace 4 min'),
('94', 'Guainía', 'Inírida', 2.831, -68.86, 'Conversación sobre testigos electorales', '["Elecciones2026","CNE","Instagram","Guainía"]', 'positivo', '{"positivo":68,"neutral":9,"negativo":23}', 14240, '{"Instagram":14240}', 'Conversación en Instagram en Guainía centrada en el proceso electoral 2026. Capital: Inírida.', 'baja', -2.3, '["#Elecciones2026","#CNEColombia","#Guainía"]', 'hace 5 min'),
('95', 'Guaviare', 'San José del Guaviare', 1.914, -71.868, 'Cobertura de campañas y candidatos en Instagram', '["Elecciones2026","CNE","Instagram","Guaviare"]', 'neutral', '{"positivo":40,"neutral":52,"negativo":8}', 11600, '{"Instagram":11600}', 'Conversación en Instagram en Guaviare centrada en el proceso electoral 2026. Capital: San José del Guaviare.', 'sube', 1.2, '["#Elecciones2026","#CNEColombia","#Guaviare"]', 'hace 6 min'),
('97', 'Vaupés', 'Mitú', 0.321, -70.573, 'Reels sobre cédula y puestos de votación', '["Elecciones2026","CNE","Instagram","Vaupés"]', 'neutral', '{"positivo":47,"neutral":42,"negativo":11}', 10580, '{"Instagram":10580}', 'Conversación en Instagram en Vaupés centrada en el proceso electoral 2026. Capital: Mitú.', 'estable', 4.4, '["#Elecciones2026","#CNEColombia","#Vaupés"]', 'hace 7 min'),
('99', 'Vichada', 'Puerto Carreño', 4.252, -69.261, 'Debates y propuestas de actores electorales', '["Elecciones2026","CNE","Instagram","Vichada"]', 'neutral', '{"positivo":54,"neutral":32,"negativo":14}', 12440, '{"Instagram":12440}', 'Conversación en Instagram en Vichada centrada en el proceso electoral 2026. Capital: Puerto Carreño.', 'baja', 7.9, '["#Elecciones2026","#CNEColombia","#Vichada"]', 'hace 8 min')
ON CONFLICT (id) DO NOTHING;
