-- Tabla para las métricas generales de Legitimidad (Indices)
CREATE TABLE IF NOT EXISTS content_manager_legitimidad_indices (
    id TEXT PRIMARY KEY, -- 'main'
    indice_confianza INTEGER DEFAULT 74,
    indice_transparencia INTEGER DEFAULT 82,
    indice_eficiencia INTEGER DEFAULT 68,
    encuestas JSONB DEFAULT '[]' -- Datos para el gráfico de línea
);

-- Tabla para las certificaciones de Legitimidad
CREATE TABLE IF NOT EXISTS content_manager_legitimidad_certificaciones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    exp TEXT NOT NULL
);

-- Tabla para las acciones de transparencia
CREATE TABLE IF NOT EXISTS content_manager_legitimidad_acciones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    accion TEXT NOT NULL,
    avance INTEGER DEFAULT 0
);

-- Tabla para la estrategia de Legitimidad (Pestañas TopicTabs)
CREATE TABLE IF NOT EXISTS content_manager_legitimidad_strategy (
    id TEXT PRIMARY KEY, -- 'main'
    narrativa JSONB DEFAULT '{}',
    pilares JSONB DEFAULT '[]',
    noticias JSONB DEFAULT '[]',
    contenido JSONB DEFAULT '{}',
    conversacion JSONB DEFAULT '{}',
    pauta JSONB DEFAULT '[]'
);

-- Insertar datos iniciales para Índices
INSERT INTO content_manager_legitimidad_indices (id, indice_confianza, indice_transparencia, indice_eficiencia, encuestas) VALUES
('main', 74, 82, 68, '[{"mes": "Dic", "confianza": 68, "transparencia": 72}, {"mes": "Ene", "confianza": 70, "transparencia": 74}, {"mes": "Feb", "confianza": 71, "transparencia": 75}, {"mes": "Mar", "confianza": 72, "transparencia": 78}, {"mes": "Abr", "confianza": 73, "transparencia": 80}, {"mes": "May", "confianza": 74, "transparencia": 81}, {"mes": "Jun", "confianza": 75, "transparencia": 82}]')
ON CONFLICT (id) DO NOTHING;

-- Insertar certificaciones inicialesNo 
INSERT INTO content_manager_legitimidad_certificaciones (nombre, exp) VALUES
('ISO 27001 — Seguridad de la Información', 'Mar 2027'),
('ISO 9001 — Gestión de Calidad', 'Dic 2026'),
('Certificación OEA — Procesos Electorales', 'Oct 2026')
ON CONFLICT DO NOTHING;

-- Insertar acciones iniciales
INSERT INTO content_manager_legitimidad_acciones (accion, avance) VALUES
('Auditoría internacional al software', 100),
('Digitalización de actas E-14', 85),
('Capacitación a jurados de votación', 60),
('Portal de datos abiertos electorales', 92)
ON CONFLICT DO NOTHING;

-- Insertar estrategia inicial (basada en mock)
INSERT INTO content_manager_legitimidad_strategy (id, narrativa, pilares, noticias, contenido, conversacion, pauta) VALUES
('main', 
 '{"gancho": "La transparencia no se promete, se audita.", "tipoConversacion": "Confianza Institucional", "mensajeClave": "Garantizamos la integridad de cada voto.", "arco": [{"fase": "Prevención", "tipo": "informativo", "mensaje": "Blindaje técnico del software."}, {"fase": "Control", "tipo": "accion", "mensaje": "Auditorías de partidos políticos."}, {"fase": "Transparencia", "tipo": "resultado", "mensaje": "Publicación inmediata de resultados."}, {"fase": "Legitimidad", "tipo": "confianza", "mensaje": "Aceptación internacional del proceso."}]}',
 '[{"pilar": "Blindaje Técnico", "icono": "🛡️", "color": "#2b82ee", "descripcion": "Seguridad multicapa en el procesamiento de datos."}, {"pilar": "Vigilancia Ciudadana", "icono": "👁️", "color": "#f3b116", "descripcion": "Acceso total a los observadores nacionales e internacionales."}, {"pilar": "Cultura de Legalidad", "icono": "⚖️", "color": "#2eb88a", "descripcion": "Respeto absoluto al marco jurídico vigente."}]',
 '[{"medio": "El Espectador", "titulo": "CNE abre sus puertas a la auditoría técnica de la OEA", "fecha": "Hace 1h", "categoria": "Institucional", "url": "#"}, {"medio": "Portafolio", "titulo": "Eficiencia en procesos electorales sube 15% este año", "fecha": "Hace 3h", "categoria": "Gestión", "url": "#"}]',
 '{"instagram": [{"formato": "Infografía", "idea": "Cómo funciona el sistema de escrutinio", "tipo": "Educativo"}], "facebook": [{"formato": "Live", "idea": "Q&A con expertos en seguridad electoral", "tipo": "Transparencia"}], "x": [{"formato": "Hilo", "idea": "Manual para detectar desinformación electoral", "tipo": "Prevención"}], "tiktok": [{"formato": "Short", "idea": "El viaje de tu voto desde la mesa al sistema", "tipo": "Explicativo"}]}',
 '{"instagram": {"menciones": 850, "sentimiento": 72, "volumePeak": "Lunes 09:00", "topHashtags": ["#Transparencia", "#CNE"]}, "facebook": {"menciones": 620, "sentimiento": 68, "volumePeak": "Martes 11:00", "topHashtags": ["#Confianza", "#Elecciones"]}, "x": {"menciones": 2800, "sentimiento": 55, "volumePeak": "Miércoles 15:00", "topHashtags": ["#AuditoriaElectoral"]}, "tiktok": {"menciones": 1500, "sentimiento": 80, "volumePeak": "Jueves 19:00", "topHashtags": ["#VotoSeguro"]}}',
 '[{"formato": "Video", "objetivo": "Alcance", "presupuesto": "Medio", "cta": "Conoce más", "segmento": "Ciudadanía General", "plataforma": ["Instagram", "YouTube"]}]'
) ON CONFLICT (id) DO NOTHING;
